In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good"]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

# One hot representation 
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[885, 8395, 5029, 2566],
 [885, 8395, 5029, 7330],
 [885, 7397, 5029, 6142],
 [3121, 8946, 3647, 3995, 6764],
 [3121, 8946, 3647, 3995, 8791],
 [5400, 885, 8353, 5029, 3551],
 [325, 914, 920, 3995]]

In [5]:
# Word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = "pre", maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0  885 8395 5029 2566]
 [   0    0    0    0  885 8395 5029 7330]
 [   0    0    0    0  885 7397 5029 6142]
 [   0    0    0 3121 8946 3647 3995 6764]
 [   0    0    0 3121 8946 3647 3995 8791]
 [   0    0    0 5400  885 8353 5029 3551]
 [   0    0    0    0  325  914  920 3995]]


In [7]:
# Feature representation
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile(optimizer="adam", loss="mse")

c:\Users\mohit\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[[-4.96909879e-02, -2.81681865e-03,  2.39420868e-02,
          1.50723122e-02,  4.86912169e-02,  2.50798948e-02,
         -1.28213875e-02, -2.38702428e-02, -3.70360725e-02,
         -3.48489657e-02],
        [-4.96909879e-02, -2.81681865e-03,  2.39420868e-02,
          1.50723122e-02,  4.86912169e-02,  2.50798948e-02,
         -1.28213875e-02, -2.38702428e-02, -3.70360725e-02,
         -3.48489657e-02],
        [-4.96909879e-02, -2.81681865e-03,  2.39420868e-02,
          1.50723122e-02,  4.86912169e-02,  2.50798948e-02,
         -1.28213875e-02, -2.38702428e-02, -3.70360725e-02,
         -3.48489657e-02],
        [-4.96909879e-02, -2.81681865e-03,  2.39420868e-02,
          1.50723122e-02,  4.86912169e-02,  2.50798948e-02,
         -1.28213875e-02, -2.38702428e-02, -3.70360725e-02,
         -3.48489657e-02],
        [ 1.26733892e-02, -3.19296122e-02,  3.56154181e-02,
          3.97531278e-02,  3.83062474e-02, -1.81504712e-02,
          5.25307655e-03,  3.71515639e-02, -3.135110

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0,  885, 8395, 5029, 2566])